language: node_js
node_js:
  - node
  - 7
  - 6
cache:
  yarn: true
  directories:
    - "node_modules"
install:
  - npm install -g codecov
before_script:
  - npm install
script:
  - npm test
after_success:
  - codecov
